-- phpMyAdmin SQL Dump
-- version 3.5.1
-- http://www.phpmyadmin.net
--
-- Client: localhost
-- Généré le: Sam 25 Mai 2013 à 16:52
-- Version du serveur: 5.5.24-log
-- Version de PHP: 5.4.3

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données: `killamaury`
--

-- --------------------------------------------------------

--
-- Structure de la table `id_minecraft`
--

CREATE TABLE IF NOT EXISTS `id_minecraft` (
  `id` int(11) NOT NULL,
  `name` varchar(200) NOT NULL,
  `description` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Contenu de la table `id_minecraft`
--

INSERT INTO `id_minecraft` (`id`, `name`, `description`) VALUES
(0, 'Air', 'L''air est un bloc invisible, non solide, qui est supposé représenter l''absence de bloc. Bien qu''étant techniquement un bloc comme un autre il n''est pas considéré comme tel. L''air ne peut être détruit ou placé qu''en plaçant ou en retirant un bloc quelconque. L''air et tous les blocs non-solides en général sont les seuls blocs qui permettent au joueur et aux créatures de se déplacer à travers.'),
(1, 'Roche (Stone)', 'La roche (nom anglais : stone), également connue sous le nom de pierre lisse, est un type de bloc ajouté lors des premières versions de Minecraft. La roche apparaît abondamment sur toute carte générée naturellement, et est (en dehors de l''air) le bloc le plus répandu : les cavernes en sont essentiellement constituées'),
(2, 'Herbe (Grass)', 'L''herbe (nom anglais : grass) est un bloc introduit très tôt dans le jeu. Elle peut apparaître sur les blocs d''une couche de terre ayant leur face supérieure exposée à une certaine intensité de lumière, et n''étant pas recouverte par du feuillage ou un fluide.\r\nEn la creusant, l''herbe se comporte comme de la terre, puisqu''elle donne une ressource de terre et est à extraire de préférence avec une pelle ; cependant, elle produit un son différent, et met un peu plus de temps à creuser. Ce dernier détail permet par exemple aux joueurs creusant vers le haut de savoir s''ils sont sur le point d''atteindre la surface. Il est possible de récupérer un bloc d''herbe dans son inventaire grâce à l''enchantement nommé "Délicatesse".'),
(3, 'Terre (Dirt)', 'La terre, communément appelée bouse (nom anglais : dirt) est l''un des premiers blocs créés dans le jeu. Les six faces possédent la même texture. C''est un matériau très courant sur les cartes générées naturellement, qui recouvre toutes les couches de blocs entre l''herbe ou neige et la roche. C''est un bloc très fragile qui peut facilement être détruit avec du TNT ou par des creepers. Par conséquent les abris en terre sont une solution à éviter, sauf en dernier recours.'),
(4, 'Pierre (Cobblestone)', 'La pierre (nom anglais : cobblestone) est un bloc des plus simples à obtenir, ressemblant à de la roche grossièrement pavée. Il s''agit d''un élément de base pour de nombreuses recettes d''artisanat ; de plus, la pierre, grâce à sa solidité, son apparence et son abondance, est généralement le principal matériau utilisé pour faire de grandes constructions, telles que des châteaux, des tours ou des routes.'),
(5, 'Planche (wooden plank)', 'Les planches (nom anglais : wooden plank) sont des blocs fabriqués à partir de bois. Elles ont l''apparence de séries de planches interconnectées, et sont rencontrées naturellement dans les mines abandonnées, les forts et les villages de PNJ. Souvent utilisées comme matériau de construction, elles sont un ingrédient nécessaire à de nombreuses recettes. Les planches font partie des ressources renouvelables, et peuvent être facilement obtenues en grande quantité dans les biomes de forêts ou par l''entretien de forêts artificielles'),
(6, 'Pousses d''arbre (sapling)', 'Les pousses d''arbre (nom anglais : sapling) sont des ressources importantes qui permettent de faire pousser des arbres pour remplacer ceux coupés par les mineurs à la recherche de bois, de planches ou de bâtons.\r\nIl existe plusieurs types de pousses, provenant des quatre types d''arbres existants : les chênes (arbres normaux), les bouleaux, les épicéas et les arbres tropicaux. Mise à part leur apparence et le type de bois qu''ils produisent, les pousses d''arbre ont toutes les mêmes propriétés.'),
(7, 'Bedrock', 'La bedrock est un bloc indestructible qui délimite la couche inférieure de la carte. La bedrock ne peut pas être miné ni détruit en mode survie, et ne peut être retiré qu''en mode Créatif ou en utilisant un programme d''édition de carte. La bedrock a une texture modifiée (avec un contraste plus important) d''un bloc de roche.'),
(8, 'Eau (water)', 'L''eau (nom anglais : water) est un fluide pouvant être placé par le joueur uniquement à l''aide d''un seau. Sur des cartes fraîchement générées, l''eau est commune à l''altitude 0 (niveau de l''océan, élévation 63) sous la forme de lacs. Elle apparaît également sous forme de piscines, (et de sources en Indev, Infdev, Alpha, et Bêta) et sous forme de rivières souterraines en dessous de la surface du sol.'),
(9, 'Eau stationnaire (water)', 'L''eau (nom anglais : water) est un fluide pouvant être placé par le joueur uniquement à l''aide d''un seau. Sur des cartes fraîchement générées, l''eau est commune à l''altitude 0 (niveau de l''océan, élévation 63) sous la forme de lacs. Elle apparaît également sous forme de piscines, (et de sources en Indev, Infdev, Alpha, et Bêta) et sous forme de rivières souterraines en dessous de la surface du sol.'),
(10, 'Lave (Lava)', 'La lave (nom anglais : lava) est un fluide. Les sources de lave sont ordinairement trouvées en profondeur sous forme de lacs, et occasionnellement en surface. Les sources de lave sont aussi très communes dans le Nether. Le contact avec la lave est dangereux, et inflige des dommages aux joueurs et aux créatures, sauf les cochons zombie, les ghasts et les Blazes ainsi que les Wither squelettes'),
(11, 'Lave stationnaire (Lava)', 'La lave (nom anglais : lava) est un fluide. Les sources de lave sont ordinairement trouvées en profondeur sous forme de lacs, et occasionnellement en surface. Les sources de lave sont aussi très communes dans le Nether. Le contact avec la lave est dangereux, et inflige des dommages aux joueurs et aux créatures, sauf les cochons zombie, les ghasts et les Blazes ainsi que les Wither squelettes'),
(12, 'Sable (Sand)', 'Le sable (nom anglais : sand) est un bloc assez courant que l''on trouve près de l''eau sur les cartes générées naturellement. Ses six faces possèdent la même texture. Comme le gravier et l''œuf d''Enderdragon, il est soumis à la gravité et tombera sur le premier bloc solide à la verticale de la position où il se trouve. Si un bloc de sable tombe sur une créature ou un joueur et recouvre sa tête, il suffoquera jusqu''à ce qu''il détruise ou sorte du bloc.'),
(13, 'Gravier (Gravel)', 'Le gravier (nom anglais : gravel) est un type de bloc généralement trouvé sous forme de carrières naturelles, sous l''eau, sous terre ou encore dans le Nether. Comme le sable et l''oeuf d''Enderdragon, le gravier tombe naturellement tant qu''il n''y a pas de bloc solide sous lui. Ainsi, il est possible de se blesser par suffocation en se faisant ensevelir sous du gravier. Si le bloc situé sous le gravier est une torche ou un demi-bloc (dalles, répéteurs, etc.), le gravier se cassera automatiquement pour être récupérable par le joueur.'),
(14, 'Minerai d''or (Gold ore)', 'Le minerai d''or (nom anglais : gold ore) est un bloc trouvé communément parmi des blocs de roche à grande profondeur, généralement en un filon de 4 à 6 blocs. L''or est le 3e matériau le plus rare après le diamant et l''émeraude. Il apparaît à des niveaux compris entre le niveau 0 (la base de la carte) et le niveau 35 (à peu près à mi-chemin entre la base de la carte et le niveau de la mer). Il constitue 0,1% de la couche située entre le niveau 0 et le niveau 32. Au-dessus, sa concentration décroît nettement. Il peut être extrait avec une pioche en fer ou plus. Une pioche en bois ou en pierre, ou un outil différent, provoquerait la destruction du bloc sans la récolte du minerai. L''or obtenu peut être fondu dans un four pour créer des lingots d''or. Par sa fragilité, l''or est plus utilisé pour son caractère décoratif que pour son efficacité lors de la confection d''armures ou d''objets. L''or (en lingot) sert également à la confection de montres et de rails de propulsion.'),
(15, 'Minerai de fer (iron ore)', 'Le minerai de fer (nom anglais : iron ore) est un minerai assez peu fréquent, rencontré dans des zones sous-terraines de roche et parfois visible sur des falaises. Il peut être trouvé à des profondeurs de zéro (le fond de la carte) à 67 (soit 5 blocs au dessus du niveau de la mer). On le trouve dans environ 0.5% des blocs situés sous le niveau de la mer, et il est de plus en plus rare au fur et à mesure que l''on se rapproche de la surface.\r\nDans les modes Indev, Alpha et Bêta, le minerai de fer peut être fondu dans un four pour en faire des lingots de fer, un objet très utile pour la fabrication de divers objets (notamment des outils de qualité moyenne, des armures, ou encore des briquets. Depuis la Bêta, le minerai de fer nécessite au moins une pioche de pierre pour être extraite : une pioche de bois détruira le bloc sans donner de ressource.'),
(16, 'Minerai de charbon (Coal ore)', 'Le minerai de charbon (nom anglais : coal ore) est un minerai que l''on voit dans toutes les cartes. On peut en trouver dans toutes les couches, à l''intérieur des cavernes, sur les versants des falaises et sous le sol. Un morceau de charbon peut être miné directement à partir de minerai de charbon avec une pioche en bois ou mieux (autrement dit, ce n''est pas un bloc de minerai, mais plutôt un filon). Les morceaux de charbon peuvent être combinés avec des bâtons pour fabriquer des torches, ou utilisés comme combustible dans un four ou dans un chariot motorisé. Quand il brûle dans un four, il permet de faire fondre jusqu''à 8 exemplaires d''un objet pour chaque morceau de charbon.\r\nDepuis la version officielle de Minecraft, miner du charbon rapporte un morceau de charbon. Les blocs de charbon sont très faciles à trouver et il s''agit du seul minerai à apparaître bien au-dessus du niveau de la mer. Le minerai de charbon représente environ 1% de tous les blocs de pierre, quelle que soit l''altitude. La taille des gisements peut grandement varier : au sommet des montagnes, on n''en trouve habituellement que 5 blocs, alors que sous terre, on peut trouver des gisements de 10 à 15 blocs sans que ce soit inhabituel.'),
(17, 'Bois (Wood)', 'Le bois (nom anglais : wood ou anciennement log) est un type de bloc vu pour la première fois dans Minecraft Créatif 0.0.14a. Il a une texture ressemblant à de l''écorce sur les quatre côtés, et à une coupe de bois sur le haut et le bas. Le bois est extrêmement présent dans les cartes naturellement générées puisqu''il est utilisé comme base des arbres. Le bois peut être récolté à la main, bien que l''utilisation d''une hache accélère le processus. Le bois est inflammable, mais dans certaines conditions ne brulera jamais (voir feu). Des arbres brulés laisseront généralement 1 à 3 blocs de bois encore en feu. Il est possible d''obtenir des planches de teinte variable suivant le type de bois.'),
(18, 'Feuillage (Leaves)', 'Le feuillage (nom anglais : leaves) est un type de bloc trouvé en grande quantité dans toutes les cartes, puisqu''ils apparaissent à chaque fois sur les arbres. Ils peuvent adopter des textures différentes, avec des couleurs qui varient, mais la même texture est représentée sur les 6 faces du bloc.'),
(19, 'Éponge (Sponge)', 'L''éponge (nom anglais : sponge) est un bloc particulier car il permet d''absorber l''eau dans une zone de 5x5x5 blocs. Cependant cette fonctionnalité n''existe que dans la version classique ; depuis la Bêta, ce bloc n''a pas d''utilité particulière.\r\nL''éponge ne peut être obtenue en tant que bloc de construction que dans le mode Créatif. Cependant vous pouvez l''obtenir en utilisant un éditeur d''inventaire. En mode Survie ou Créatif, les éponges n''ont pas de propriétés absorbantes. Elles agissent comme le feraient des blocs de roche, mais en plus fragile. Cependant, détruire une éponge située à proximité de trappe(s) ouverte(s) les referme automatiquement.'),
(20, 'Verre (Glass)', 'Le verre (nom anglais : glass) est un bloc qui est apparu dans le mode créatif, version 0.0.18a_02. Il a une texture en grande partie transparente sur ses six faces. Ce n''est pas un bloc naturel, il n''est jamais généré avec le terrain. Il est généralement utilisé comme matériau de construction, soit tel quel, soit une fois transformé en vitres.'),
(21, 'Minerai de lapis-lazuli', 'Le minerai de lapis-lazuli (nom anglais : lapis lazuli ore) est un bloc de minerai. Il peut être utilisé pour créer du colorant bleu ou et des blocs décoratifs. De la même manière que le charbon, la redstone, et le diamant, la ressource est utilisable directement après le minage et elle ne requiert pas de transformation ou de fonte. Chaque bloc donne 4 à 8 colorants bleus, qui peuvent être utilisés pour créer de la laine bleue ou des blocs de lapis-lazuli. Ils peuvent aussi être mélangées avec d''autres colorants.');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
