-- phpMyAdmin SQL Dump
-- version 3.5.1
-- http://www.phpmyadmin.net
--
-- Client: localhost
-- Généré le: Mar 28 Mai 2013 à 18:41
-- Version du serveur: 5.5.24-log
-- Version de PHP: 5.4.3

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données: `killamaury`
--

-- --------------------------------------------------------

--
-- Structure de la table `id_minecraft`
--

CREATE TABLE IF NOT EXISTS `id_minecraft` (
  `id` int(11) NOT NULL,
  `name` varchar(200) NOT NULL,
  `description` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Contenu de la table `id_minecraft`
--

INSERT INTO `id_minecraft` (`id`, `name`, `description`) VALUES
(0, 'Air', 'L''air est un bloc invisible, non solide, qui est supposé représenter l''absence de bloc. Bien qu''étant techniquement un bloc comme un autre il n''est pas considéré comme tel. L''air ne peut être détruit ou placé qu''en plaçant ou en retirant un bloc quelconque. L''air et tous les blocs non-solides en général sont les seuls blocs qui permettent au joueur et aux créatures de se déplacer à travers.'),
(1, 'Roche (Stone)', 'La roche (nom anglais : stone), également connue sous le nom de pierre lisse, est un type de bloc ajouté lors des premières versions de Minecraft. La roche apparaît abondamment sur toute carte générée naturellement, et est (en dehors de l''air) le bloc le plus répandu : les cavernes en sont essentiellement constituées'),
(2, 'Herbe (Grass)', 'L''herbe (nom anglais : grass) est un bloc introduit très tôt dans le jeu. Elle peut apparaître sur les blocs d''une couche de terre ayant leur face supérieure exposée à une certaine intensité de lumière, et n''étant pas recouverte par du feuillage ou un fluide.\r\nEn la creusant, l''herbe se comporte comme de la terre, puisqu''elle donne une ressource de terre et est à extraire de préférence avec une pelle ; cependant, elle produit un son différent, et met un peu plus de temps à creuser. Ce dernier détail permet par exemple aux joueurs creusant vers le haut de savoir s''ils sont sur le point d''atteindre la surface. Il est possible de récupérer un bloc d''herbe dans son inventaire grâce à l''enchantement nommé "Délicatesse".'),
(3, 'Terre (Dirt)', 'La terre, communément appelée bouse (nom anglais : dirt) est l''un des premiers blocs créés dans le jeu. Les six faces possédent la même texture. C''est un matériau très courant sur les cartes générées naturellement, qui recouvre toutes les couches de blocs entre l''herbe ou neige et la roche. C''est un bloc très fragile qui peut facilement être détruit avec du TNT ou par des creepers. Par conséquent les abris en terre sont une solution à éviter, sauf en dernier recours.'),
(4, 'Pierre (Cobblestone)', 'La pierre (nom anglais : cobblestone) est un bloc des plus simples à obtenir, ressemblant à de la roche grossièrement pavée. Il s''agit d''un élément de base pour de nombreuses recettes d''artisanat ; de plus, la pierre, grâce à sa solidité, son apparence et son abondance, est généralement le principal matériau utilisé pour faire de grandes constructions, telles que des châteaux, des tours ou des routes.'),
(5, 'Planche (wooden plank)', 'Les planches (nom anglais : wooden plank) sont des blocs fabriqués à partir de bois. Elles ont l''apparence de séries de planches interconnectées, et sont rencontrées naturellement dans les mines abandonnées, les forts et les villages de PNJ. Souvent utilisées comme matériau de construction, elles sont un ingrédient nécessaire à de nombreuses recettes. Les planches font partie des ressources renouvelables, et peuvent être facilement obtenues en grande quantité dans les biomes de forêts ou par l''entretien de forêts artificielles'),
(6, 'Pousses d''arbre (sapling)', 'Les pousses d''arbre (nom anglais : sapling) sont des ressources importantes qui permettent de faire pousser des arbres pour remplacer ceux coupés par les mineurs à la recherche de bois, de planches ou de bâtons.\r\nIl existe plusieurs types de pousses, provenant des quatre types d''arbres existants : les chênes (arbres normaux), les bouleaux, les épicéas et les arbres tropicaux. Mise à part leur apparence et le type de bois qu''ils produisent, les pousses d''arbre ont toutes les mêmes propriétés.'),
(7, 'Bedrock', 'La bedrock est un bloc indestructible qui délimite la couche inférieure de la carte. La bedrock ne peut pas être miné ni détruit en mode survie, et ne peut être retiré qu''en mode Créatif ou en utilisant un programme d''édition de carte. La bedrock a une texture modifiée (avec un contraste plus important) d''un bloc de roche.'),
(8, 'Eau (water)', 'L''eau (nom anglais : water) est un fluide pouvant être placé par le joueur uniquement à l''aide d''un seau. Sur des cartes fraîchement générées, l''eau est commune à l''altitude 0 (niveau de l''océan, élévation 63) sous la forme de lacs. Elle apparaît également sous forme de piscines, (et de sources en Indev, Infdev, Alpha, et Bêta) et sous forme de rivières souterraines en dessous de la surface du sol.'),
(9, 'Eau stationnaire (water)', 'L''eau (nom anglais : water) est un fluide pouvant être placé par le joueur uniquement à l''aide d''un seau. Sur des cartes fraîchement générées, l''eau est commune à l''altitude 0 (niveau de l''océan, élévation 63) sous la forme de lacs. Elle apparaît également sous forme de piscines, (et de sources en Indev, Infdev, Alpha, et Bêta) et sous forme de rivières souterraines en dessous de la surface du sol.'),
(10, 'Lave (Lava)', 'La lave (nom anglais : lava) est un fluide. Les sources de lave sont ordinairement trouvées en profondeur sous forme de lacs, et occasionnellement en surface. Les sources de lave sont aussi très communes dans le Nether. Le contact avec la lave est dangereux, et inflige des dommages aux joueurs et aux créatures, sauf les cochons zombie, les ghasts et les Blazes ainsi que les Wither squelettes'),
(11, 'Lave stationnaire (Lava)', 'La lave (nom anglais : lava) est un fluide. Les sources de lave sont ordinairement trouvées en profondeur sous forme de lacs, et occasionnellement en surface. Les sources de lave sont aussi très communes dans le Nether. Le contact avec la lave est dangereux, et inflige des dommages aux joueurs et aux créatures, sauf les cochons zombie, les ghasts et les Blazes ainsi que les Wither squelettes'),
(12, 'Sable (Sand)', 'Le sable (nom anglais : sand) est un bloc assez courant que l''on trouve près de l''eau sur les cartes générées naturellement. Ses six faces possèdent la même texture. Comme le gravier et l''œuf d''Enderdragon, il est soumis à la gravité et tombera sur le premier bloc solide à la verticale de la position où il se trouve. Si un bloc de sable tombe sur une créature ou un joueur et recouvre sa tête, il suffoquera jusqu''à ce qu''il détruise ou sorte du bloc.'),
(13, 'Gravier (Gravel)', 'Le gravier (nom anglais : gravel) est un type de bloc généralement trouvé sous forme de carrières naturelles, sous l''eau, sous terre ou encore dans le Nether. Comme le sable et l''oeuf d''Enderdragon, le gravier tombe naturellement tant qu''il n''y a pas de bloc solide sous lui. Ainsi, il est possible de se blesser par suffocation en se faisant ensevelir sous du gravier. Si le bloc situé sous le gravier est une torche ou un demi-bloc (dalles, répéteurs, etc.), le gravier se cassera automatiquement pour être récupérable par le joueur.'),
(14, 'Minerai d''or (Gold ore)', 'Le minerai d''or (nom anglais : gold ore) est un bloc trouvé communément parmi des blocs de roche à grande profondeur, généralement en un filon de 4 à 6 blocs. L''or est le 3e matériau le plus rare après le diamant et l''émeraude. Il apparaît à des niveaux compris entre le niveau 0 (la base de la carte) et le niveau 35 (à peu près à mi-chemin entre la base de la carte et le niveau de la mer). Il constitue 0,1% de la couche située entre le niveau 0 et le niveau 32. Au-dessus, sa concentration décroît nettement. Il peut être extrait avec une pioche en fer ou plus. Une pioche en bois ou en pierre, ou un outil différent, provoquerait la destruction du bloc sans la récolte du minerai. L''or obtenu peut être fondu dans un four pour créer des lingots d''or. Par sa fragilité, l''or est plus utilisé pour son caractère décoratif que pour son efficacité lors de la confection d''armures ou d''objets. L''or (en lingot) sert également à la confection de montres et de rails de propulsion.'),
(15, 'Minerai de fer (iron ore)', 'Le minerai de fer (nom anglais : iron ore) est un minerai assez peu fréquent, rencontré dans des zones sous-terraines de roche et parfois visible sur des falaises. Il peut être trouvé à des profondeurs de zéro (le fond de la carte) à 67 (soit 5 blocs au dessus du niveau de la mer). On le trouve dans environ 0.5% des blocs situés sous le niveau de la mer, et il est de plus en plus rare au fur et à mesure que l''on se rapproche de la surface.\r\nDans les modes Indev, Alpha et Bêta, le minerai de fer peut être fondu dans un four pour en faire des lingots de fer, un objet très utile pour la fabrication de divers objets (notamment des outils de qualité moyenne, des armures, ou encore des briquets. Depuis la Bêta, le minerai de fer nécessite au moins une pioche de pierre pour être extraite : une pioche de bois détruira le bloc sans donner de ressource.'),
(16, 'Minerai de charbon (Coal ore)', 'Le minerai de charbon (nom anglais : coal ore) est un minerai que l''on voit dans toutes les cartes. On peut en trouver dans toutes les couches, à l''intérieur des cavernes, sur les versants des falaises et sous le sol. Un morceau de charbon peut être miné directement à partir de minerai de charbon avec une pioche en bois ou mieux (autrement dit, ce n''est pas un bloc de minerai, mais plutôt un filon). Les morceaux de charbon peuvent être combinés avec des bâtons pour fabriquer des torches, ou utilisés comme combustible dans un four ou dans un chariot motorisé. Quand il brûle dans un four, il permet de faire fondre jusqu''à 8 exemplaires d''un objet pour chaque morceau de charbon.\r\nDepuis la version officielle de Minecraft, miner du charbon rapporte un morceau de charbon. Les blocs de charbon sont très faciles à trouver et il s''agit du seul minerai à apparaître bien au-dessus du niveau de la mer. Le minerai de charbon représente environ 1% de tous les blocs de pierre, quelle que soit l''altitude. La taille des gisements peut grandement varier : au sommet des montagnes, on n''en trouve habituellement que 5 blocs, alors que sous terre, on peut trouver des gisements de 10 à 15 blocs sans que ce soit inhabituel.'),
(17, 'Bois (Wood)', 'Le bois (nom anglais : wood ou anciennement log) est un type de bloc vu pour la première fois dans Minecraft Créatif 0.0.14a. Il a une texture ressemblant à de l''écorce sur les quatre côtés, et à une coupe de bois sur le haut et le bas. Le bois est extrêmement présent dans les cartes naturellement générées puisqu''il est utilisé comme base des arbres. Le bois peut être récolté à la main, bien que l''utilisation d''une hache accélère le processus. Le bois est inflammable, mais dans certaines conditions ne brulera jamais (voir feu). Des arbres brulés laisseront généralement 1 à 3 blocs de bois encore en feu. Il est possible d''obtenir des planches de teinte variable suivant le type de bois.'),
(18, 'Feuillage (Leaves)', 'Le feuillage (nom anglais : leaves) est un type de bloc trouvé en grande quantité dans toutes les cartes, puisqu''ils apparaissent à chaque fois sur les arbres. Ils peuvent adopter des textures différentes, avec des couleurs qui varient, mais la même texture est représentée sur les 6 faces du bloc.'),
(19, 'Éponge (Sponge)', 'L''éponge (nom anglais : sponge) est un bloc particulier car il permet d''absorber l''eau dans une zone de 5x5x5 blocs. Cependant cette fonctionnalité n''existe que dans la version classique ; depuis la Bêta, ce bloc n''a pas d''utilité particulière.\r\nL''éponge ne peut être obtenue en tant que bloc de construction que dans le mode Créatif. Cependant vous pouvez l''obtenir en utilisant un éditeur d''inventaire. En mode Survie ou Créatif, les éponges n''ont pas de propriétés absorbantes. Elles agissent comme le feraient des blocs de roche, mais en plus fragile. Cependant, détruire une éponge située à proximité de trappe(s) ouverte(s) les referme automatiquement.'),
(20, 'Verre (Glass)', 'Le verre (nom anglais : glass) est un bloc qui est apparu dans le mode créatif, version 0.0.18a_02. Il a une texture en grande partie transparente sur ses six faces. Ce n''est pas un bloc naturel, il n''est jamais généré avec le terrain. Il est généralement utilisé comme matériau de construction, soit tel quel, soit une fois transformé en vitres.'),
(21, 'Minerai de lapis-lazuli', 'Le minerai de lapis-lazuli (nom anglais : lapis lazuli ore) est un bloc de minerai. Il peut être utilisé pour créer du colorant bleu ou et des blocs décoratifs. De la même manière que le charbon, la redstone, et le diamant, la ressource est utilisable directement après le minage et elle ne requiert pas de transformation ou de fonte. Chaque bloc donne 4 à 8 colorants bleus, qui peuvent être utilisés pour créer de la laine bleue ou des blocs de lapis-lazuli. Ils peuvent aussi être mélangées avec d''autres colorants.'),
(22, 'Bloc de lapis-lazuli (Lapis-lazuli block)', 'Le bloc de lapis-lazuli (nom anglais : lapis lazuli block) peut être fabriqué à partir de neuf colorants de lapis-lazuli. Il a une couleur bleue, et est similaire aux blocs d''or et autres blocs de métal. Il sert principalement à stocker le colorant de lapis-lazuli, mais est aussi utilisé comme bloc décoratif.'),
(23, 'Distributeur (Dispenser)', 'Un distributeur (nom anglais : dispenser) est un bloc spécial disponible depuis la version Bêta 1.2. Lorsque vous faites un clic droit dessus, un menu vous propose de poser des objets dedans. À chaque fois que le distributeur reçoit du courant depuis un circuit de redstone, un des objets qu''il contient est envoyé aléatoirement. Le distributeur ressemble au four, mais ces deux blocs ont des usages et des recettes de fabrication différents.'),
(24, 'Grès (Sandstone)', 'Le grès (nom anglais : sandstone) est un bloc solide, présent naturellement sous le sable ainsi que dans certaines structures naturelles (pyramides et puits), et récupérable à l''aide d''une pioche. Le grès peut être fabriqué en plaçant quatre blocs de sable dans une table de fabrication. Contrairement à ce dernier, il n''est pas soumis à la gravité. Le grès est utilisé comme matériau de construction ou bien pour fabriquer des escaliers, des dalles de grès ou encore des blocs de grès poli.'),
(25, 'Bloc musical (Note block)', 'Le bloc musical (nom anglais : note block) est un bloc se présentant sous la forme d''une boîte, et qui est capable de produire un son musical. Le son produit par un bloc musical dépend du bloc sur lequel il est placé, ainsi que de la manière dont il a été accordé. En combinant plusieurs blocs musicaux à l''aide de circuits de redstone, il est possible de créer des mélodies voire des musiques entières.'),
(26, 'Lits (Bed)', 'Les lits (nom anglais : bed) sont des blocs permettent aux joueurs d''avancer le cycle jour/nuit jusqu''à la prochaine aube. En multijoueur, cela ne fonctionnera que si tous les joueurs du serveur dorment simultanément. Les lits ont été ajoutés dans la Bêta 1.3[1]. Depuis la mise à jour Bêta 1.4, le dernier lit dans lequel un joueur a dormi sert de point de départ la prochaine fois qu''il sera tué. Les lits ne peuvent pas être détruits par le feu.'),
(27, 'Rails de propulsion (Powered rails)', 'Les rails de propulsion (nom anglais : powered rails) sont des blocs disponibles depuis la Bêta 1.5. Ils se veulent une alternative aux boosters qui exploitaient les bugs du jeu jusqu''à être corrigés par la mise à jour Bêta 1.6. Lorsqu''un rail de propulsion est alimenté, il donne de la vitesse à tout chariot roulant dessus. En revanche, s''il est éteint, il agit comme un frein, bloquant les chariots les atteignant.'),
(28, 'Rails de détection (Detector rail)', 'Les rails de détection (nom anglais : detector rail) sont des blocs ajoutés lors de la version Bêta 1.5[1]. Ils fonctionnent comme les plaques de détection, mais sous la forme de rails, permettant ainsi à des chariots de mine de circuler dessus. Leur texture lorsqu''ils sont actifs a été implémentée dans la version hebdomadaire 13w10a (1.5), soit longtemps après leur ajout.\r\nLorsqu''un chariot de n''importe quel type, occupé ou non, roule sur un rail de détection, cela génèrera un signal de redstone. Le signal sera transmis aux blocs adjacents au détecteur (y compris des rails de propulsion), ainsi qu''à toute redstone placée sous le rail : le comportement est donc exactement le même que celui d''une plaque de détection.'),
(29, 'Piston collants (Sticky piston)', 'Les pistons collants (nom anglais : sticky piston) sont des blocs implantés durant la mise à jour 1.7. Ils peuvent être créés en ajoutant une boule de slime au dessus d''un piston.\r\nLes pistons collants, comme leur nom l''indique, « collent » à l''objet qu''ils poussent, et, de ce fait, le tirent en se contractant. Le seul moyen de séparer un bloc d''un piston collant est soit de détruire le bloc ou le piston, soit de pousser le bloc à l''aide d''un second piston.'),
(30, 'Toile d''araignée', 'La toile d''araignée (nom anglais : cobweb) est un bloc introduit dans le jeu avec la mise à jour Bêta 1.8. On peut trouver des toiles d''araignées dans les puits de mine abandonnés non loin des générateurs d''araignées bleues ou encore dans les forts, surtout dans les bibliothèques.\r\nLes toiles d''araignées sont présentes dans le code du jeu depuis la version Bêta 1.5, mais ne pouvaient pas être obtenues autrement qu''avec édition d''inventaire, ou bien avec un /give en multijoueur. Elle était déjà présente dans le fichier terrain.png auparavant, mais n''avait pas de bloc associé. La version Bêta 1.8 a donc permis leur génération avec le terrain, dans le cas des mines abandonnées, par exemple, ou bien dynamiquement, étant donné que les araignées bleues peuvent en créer.'),
(31, 'Herbes hautes ', 'Les herbes hautes sont un bloc introduit dans la version Bêta 1.6[1]. Elles apparaissent sur les blocs d''herbe dans certains biomes, généralement en grandes quantités. Des graines de blé peuvent être obtenues en détruisant ce type de bloc, sans qu''une houe ne soit nécessaire. Elles peuvent néanmoins être récupérées puis replantées grâce aux Cisailles depuis la mise à jour 1.8.'),
(32, 'Arbustes morts (Dead bush)', 'Les arbustes morts (nom anglais : dead bush) sont des blocs qui ont été ajoutés dans la Bêta 1.6, et ne doivent pas être confondus avec les herbes hautes, qui leur ressemblent assez. Ce ne sont pas des blocs solides, mais plutôt des mauvaises herbes esthétiques qui ne gênent pas les mouvements tout comme la canne à sucre, le blé et les herbes hautes.\r\nLes arbustes morts apparaissent uniquement sur du sable dans les biomes du désert et ne produisent aucune ressource lorsqu''ils sont détruits'),
(33, 'Piston', 'Le piston est un objet disponible depuis la bêta 1.7 du 30 juin 2011. Basé sur un mod créé par Hippoplatimus, le piston offre la possibilité de pousser des blocs, des ressources ou des créatures.'),
(34, 'Tige de piston', 'Le bloc 34 est un bloc utilisé par la tige d''un piston lorsqu''elle est sortie. Un des bits de données de ce bloc permet de définir si c''est la tige d''un piston classique ou collant. Beaucoup de joueurs utilisent ce bloc en tant que table au lieu de poser une plaque de détection sur une barrière.'),
(35, 'Laine (Wool)', 'La laine (nom anglais : wool) est un bloc issu des moutons, qui peut être teint avec 16 colorants. Les blocs de laine sont inflammables et facilement destructibles par le joueur ou par les explosions.\r\nDepuis la mise à jour Bêta 1.2, les laines blanche, gris clair, grise, noire, et, depuis la version Bêta 1.4, marron et rose, peuvent être obtenues naturellement sur des moutons. Depuis la 1.7, la meilleure façon d''obtenir de la laine est de tondre les moutons à l''aide de cisailles. Frapper le mouton avec une arme, tout autre outil ou les poings aura pour conséquence de tuer l''animal, qui ne lâchera alors qu''un bloc de laine (contre un à trois avec les cisailles).\r\nIl est aussi possible de fabriquer de la laine blanche en disposant 4 fils dans une table de fabrication de 2×2 ou un établi, ce qui peut être une option intéressante depuis la version bêta 1.8 et l''introduction de toile d''araignées naturelles dans les puits de mine abandonnés. Cette option est toutefois moins efficace que la tonte et ne permet d''obtenir que de la laine blanche.'),
(36, 'Bloc déplacé par un piston', 'Le bloc 36 est un bloc utilisé par la tige d''un piston pour l''effet de l''animation sortant de la base du piston. La couleur de ce bloc lorsqu''il se situe au dessus d''un autre bloc est noire. Lorsque les blocs adjacents sont supprimés, il devient invisible, peut être traversé par le joueur et la lumière passe au travers mais en étant diminuée de 1 niveau. Il est incassable, cependant il peut être supprimé par un clic droit. Le jeu le considère comme de la roche pour l''animation de minage et le bruit des pas.'),
(37, 'Pissenlits (Dandelion)', 'Les pissenlits (nom anglais : dandelion) peuvent être collectés en un clic et peuvent être placés dans la grille de fabrication pour créer 2 pétales de pissenlit servant de colorant jaune.'),
(38, 'Roses', 'Les roses peuvent être collectées en un seul clic et placées dans une grille de fabrication pour créer 2 rouges de rose. Elles sont toujours de couleur rouge et sont un peu plus rares que les pissenlits. Elles sont le plus souvent seules ou en groupe de 3 ou 4.'),
(39, 'Champigons brun (Brows mushroom)', 'Les champignons bruns (nom anglais : brown mushroom) ne peuvent plus être mangés depuis la version Alpha. Ils doivent être mélangés avec un champignon rouge dans un bol pour donner du ragoût de champignons.\r\nAuparavant, les champignons bruns soignaient de 5 cœurs dans le mode Test de Survie, mais depuis Indev ils ne peuvent être mangés seuls. Ce champignon émet une unité de lumière, c''est à dire juste assez pour être visible dans le noir complet. Ils sont assez rares en mode Survie, mais la présence du Nether permet au joueur d''en trouver plus facilement.\r\nDepuis la version Alpha 1.2.2, il y a un bug qui noircit la texture du bloc placé en dessous d''un champignon brun. Depuis la version 1.2.3. , les champignons bruns peuvent pousser sur les feuilles des arbres de la jungle.\r\nLes champignons bruns et rouges sont détruits par une coulée d''eau, mais ils ne droppent un item que si l''eau arrive d''un coté et non pas du dessus.'),
(40, 'Champignons rouges (Red mushroom)', 'Les champignons rouges (nom anglais : red mushroom) ne peuvent plus être mangés depuis la version Bêta. Ils doivent être mélangés avec un champignon brun dans un bol pour donner du ragoût de champignons.\r\nAuparavant, les champignons rouges faisaient perdre 3 cœurs au joueur  dans le Test de Survie, mais depuis Indev ils ne peuvent être mangés seuls. Ils sont assez rares en mode Survie, mais leur présence dans le Nether permet au joueur d''en trouver plus facilement.\r\nDepuis la version 1.2.3, il est possible que des champignons rouges poussent sur les feuilles des arbres de la jungle. Ceci n''est en aucun cas un bug. Les champignons bruns peuvent aussi pousser sur les feuilles, mais il est possible que ce soit dû à un bug.'),
(41, 'Bloc d''or (Gold block)', 'Les blocs d''or (nom anglais : gold block) sont des blocs introduits par la version Créatif 0.0.20a et qui n''apparaissent pas naturellement sur une carte normalement générée.\r\nLes blocs d''or sont disponibles dans le mode Créatif, et sont souvent utilisés pour la réalisation de constructions brillantes ou « luxueuses ». Dans le mode Survie, les blocs de minerai d''or peuvent être fondus en lingots d''or, qui eux-mêmes peuvent être stockés en blocs d''or à l''aide d''un établi, à raison d''un bloc d''or pour neuf lingots. Le bloc d''or peut ensuite se fragmenter en les neuf lingots originels par un second passage sur l''établi ou l''inventaire.'),
(42, 'Bloc de fer (Iron block)', 'Le bloc de fer (nom anglais : iron block) est un bloc qui s''obtient via l''artisanat à partir de lingots de fer. L''opération inverse permettant de récupérer les lingots de fer, cela lui confère une fonction de "bloc de stockage". Le bloc de fer permet de fabriquer l''enclume.'),
(43, 'Double dalles (Double slabs)', 'Deux bloc "dalles" voir l''item "Dalles"');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
